### ISSUE TITLE
Error running "align_get_align_summary_data"

### ISSUE THREAD

**Issue by BenjaminBlanchard** [faircloth-lab/phyluce#165]
Hello! I'm having a confusing issue running `align_get_align_summary_data` for the tutorial. I've attached a screenshot of the issue:

![Screen Shot 2019-08-07 at 11 57 57 AM](https://user-images.githubusercontent.com/13558463/62642388-32d35400-b90b-11e9-9871-c73f6292ca31.png)

Is the error likely because of the "`git fatal`" issue at the top? This initially said "`fatal: Not a git repository: .git`", which I attempted to fix using "`git init`" as recommended for this error in Stack Overflow, but now it is giving this "git fatal" error. Any thoughts on what this might be?

**Comment by brantfaircloth** [comment]
Not likely due to the git error, although I'm not sure how you could get in the state where this error is thrown.  The actually error may be due to there being an empty alignment in your data set, but it is impossible to know how that may have happened without additional information.  You could use LS to look at file sizes of your alignments, then investigate anything that is very short.

**Comment by BenjaminBlanchard** [comment]
Ok, will do - thanks for the speedy reply!

**Comment by BenjaminBlanchard** [comment]
You are correct - turns out mafft-nexus-edge-trimmed is empty somehow, don't know why I didn't check this... will investigate why that happened.
