### ISSUE TITLE
phyluce_assembly_assemblo_trinity failed due to the file exists

### ISSUE THREAD

**Issue by liugang9988** [faircloth-lab/phyluce#181]
Hi,
I am now assembling the resequencing data (20X) into the fasta file. The  phyluce_assembly_assemblo_trinity has been running successful for some samples, however, for some other samples, the job failed after running for a period of time. The error report looked like below: 
###############

orm contigs using welds.
[13.4907% done]                    
##############
Traceback (most recent call last):
  File "/n/home08/gl08/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 347, in <module>
    main()
  File "/n/home08/gl08/.conda/envs/phyluce/bin/phyluce_assembly_assemblo_trinity", line 316, in main
    os.makedirs(sample_dir)
  File "/n/home08/gl08/.conda/envs/phyluce/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/n/scratchlfs/gl_lab/gl08/species_UCE/sample1_assembly/sample1_trinity'
###########

I wonder what it is going on? It's very odd to see that some samples has been successfully assembled. The same command line were used. Could you please help to solve this?

Thank you very much .

Best wishes,

Gang

**Comment by jbernst** [comment]
Hello,

Was this every solved? I am having the same exact problem. 

Best,
Justin

**Comment by brantfaircloth** [comment]
I'm not totally sure of what the problem here could be... is trinity working with the phyluce tutorial data?  if so, that suggests that there's a problem with something like sample names (e.g. 2 samples have identical names in your data set).  Alternatively, does another method for assembly work?   I would probably suggest spades over trinity...

**Comment by jbernst** [comment]
I hadn't gone back and checked. I had a college also tell me that Abyss was working really well for them. I tried Abyss and got the same error, but it was because I had not deleted the the "Taxon1_Assembly" in the "contigs" output folder, even though there were not contigs in there. So I suspect that perhaps that was my (silly...) issue when I tried Itero as well (I tried trinity first). The computer is working on assembling the other sequences, so I will have to give Itero a shot another time when these are done. But if I find that this was in fact the issue, I will post in here as an update.
