### ISSUE TITLE
SNP calling 

### ISSUE THREAD

**Issue by leonvarhan** [faircloth-lab/phyluce#253]
Hello, I was wondering what were the tools or programs in Phyluce 1.7.1 for SNP calling after phasing UCE data. Is phyluce_snp_screen_phased_alignments  no longer supported ? 
Thank you for your time !!!

**Comment by brantfaircloth** [comment]
Hello. It is no longer supported.  The SNPs calls in phased alignments should be in each of the `*.0.vcf` and `*.1.vcf` files.  I've not continued to maintain additional formatting tools because there are a number of options out there (e.g. vcf2fasta, vcftools, plink, etc.).  That said, `phyluce_snp_screen_phased_alignments` should run just fine if you install an older version of phyluce (in a conda environment, for instance).
