### ISSUE TITLE
contig correction changing bcftools flags

### ISSUE THREAD

**Issue by emilyostrow** [faircloth-lab/phyluce#269]
Hi Brant,

I was wondering if you would be able to provide some help on how to alter the correction pipeline. Your pipeline uses a QUAL value of 20 for the cutoff and I want to try 30. Is there an easy way to do this? I tried altering the Snakemake file but it gets overwritten every time I run the phyluce_workflow command

**Comment by brantfaircloth** [comment]
howdy,

you *should* be able to directly edit the appropriate snakefile that is within the phyluce conda distribution, e.g.

https://github.com/faircloth-lab/phyluce/blob/main/workflows/contig-correction/Snakefile#L60

and change `QUAL<20 | DP<5 | AN>2` to the parameters you desire.  This should not be getting overwritten by anything because it's needed for the workflow to run.  Not sure how this could be happening (that it is overwritten) - are you definitely editing the snakefile within your phyluce distribution?

**Comment by emilyostrow** [comment]
Hi Brant,

It looks like the problem was on my end with writing permissions. Thank you for the confirmation that this file was what I needed to edit. That helped a lot with figuring out the problem.

**Comment by brantfaircloth** [comment]
You bet!  I do need to make the QUAL values more modular...
