### ISSUE TITLE
arg parser issue in phyluce_align_get_informative_sites

### ISSUE THREAD

**Issue by zachrodriguez** [faircloth-lab/phyluce#51]
Arg parser wasn't consistent in `phyluce/bin/phyluce_align_get_informative_sites.py`
In main(), line 129, you have `args.input` instead of `args.alignments`
In get_args(), line 31, I changed `--alignments` to `--input` in get_args() and it worked
Adding dest=input to get_args() didn't work

**Comment by brantfaircloth** [comment]
The problem with `--alignments` versus `--input` was fixed long ago - you may not be using an up-to-date version of phyluce.  

The error you are getting is because the program isn't correctly finding the alignments - perhaps because the `--input-format` is different than expected or perhaps for some other reason.
